name: Continuos Integration

on: [push, pull_request]
  # push:
  # pull_request:
  #   branches:
  #     ['main']

jobs:
  qa_continuos_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar os arquivos do projeto
        uses: actions/checkout@v4.1.4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar as Bibliotecas do projeto
        run: |
            pip install -r requirements.txt
          
      - name: Execução dos testes 
        run: |
           robot -d results tests
          


# stages:
#     - test
  
#   variables:
#     ROBOT_OPTIONS: "--outputdir results"
  
#   test:
#     stage: test
#     image: python:3.8
  
#     before_script:
#       - pip install -r requirements.txt
  
#     script:
#       - robot $ROBOT_OPTIONS path/to/your/test/suite.robot