name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  CI_GIT:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Robot Framework & dependencies
        run: |
          pip install robotframework
          pip install robotframework-faker
          pip install robotframework-seleniumlibrary
          pip install pyautogui
          

      - name: Run tests
        run: |
          robot -d report --report index.html test_cases
        continue-on-error: true

      
      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./report