name: Continuos Integration

on: [push, pull_request]
  # push:
  # pull_request:
  #   branches:
  #     ['main']

jobs:
  qa_continuos_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar os arquivos do projeto
        uses: actions/checkout@v4.1.4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar as Bibliotecas do projeto
        run: |
            sudo apt-get update
            sudo apt-get install -y xvfb  # Instalação do Xvfb
            pip install -r requirements.txt
          
      - name: Execução dos testes com suporte gráfico 
        run: |
            # Instala o pacote xauth necessário para a autenticação X11
            sudo apt-get install -y xauth
            # Gera um novo arquivo .Xauthority (necessário para algumas configurações)
            touch ~/.Xauthority
            xauth generate :99 . trusted
            # Inicia o Xvfb em background na Display :99
            sudo Xvfb :99 -ac &
            # Configura a variável de ambiente DISPLAY
            export DISPLAY=:99
            # Executa os testes
            robot -d results test_cases
